# This is a basic workflow to help you get started with Actions

name: User CI

on:
  push:
    branches: [ main ]
    paths:
      - 'user/**'
      - '.github/workflows/user.yml'
      
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Build the project
        run: |-
          cd user
          npm ci
          npm run build
          
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - uses: actions/checkout@v2
      - name: Build the project
        run: |-
          cd user
          npm ci
          npm run test

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
